-- 20260731_alvys_invoice_backfill.sql
--
-- ONE-OFF DATA BACKFILL — not a schema change. Safe to run once.
--
-- Curzon invoiced through Alvys before FleetCal owned billing. Those
-- loads came across as `loads` rows with revenue and a billing_status,
-- but no `invoices` row was ever generated — so ~$1.97M of billed work
-- was invisible to Receivables, which reads the invoices table. This
-- reconstructs an invoice per load from what the load already knows.
--
-- The reconstruction, per Matt:
--   amount     = the load's billable total (the load amount IS the
--                invoiced amount for this era)
--   issued_at  = the load's own date, i.e. the pickup leg's start —
--                "assume the invoice was sent on the load date"
--   due_at     = issued + 30 days, so aging means something. Without a
--                due date every one of these buckets as "Current"
--                forever and a 2025 invoice reads as not-yet-due.
--   status     = paid where the load is already billing_status='paid',
--                otherwise sent
--
-- Paid ones also get an `invoice_payments` allocation. That is not
-- optional bookkeeping: invoices.paid_amount/paid_at are DERIVED from
-- the allocation ledger by recomputeInvoicePaid(), so a paid invoice
-- with no allocation is a live trap — the next write that touches it
-- recomputes applied=0 and silently flips it back to 'sent'. The
-- allocation is written so that a later recompute is a no-op:
-- paid_on = issued date, paid_at = that date at 12:00Z, method NULL,
-- which is exactly what recompute would produce.
--
-- Expected on a clean run against Curzon prod
-- (org_3Ck09w6LuEjiX4WgxJEPyiyjuXN), measured 2026-07-31:
--   invoices inserted     2560   $1,972,729.49
--     status=sent         2031   $1,635,928.71
--     status=paid          529     $336,800.78
--   allocations inserted   529     $336,800.78
--   customer_from_map      481
--   no_customer            198
--   invoices  1497 -> 4057
--   AR open   $1,149,624 -> $2,785,552.71
--   issued_at spans 2025-12-29 .. 2026-05-26
--
-- Customer resolution: 679 of these loads have no customer_id but all
-- carry a broker string, across only 89 distinct values. Those were run
-- through the app's own matcher (apps/web/lib/customerMatch.ts — the
-- same scoring the rate-con harvest uses) against the 173 customers on
-- file, and the result is baked into BROKER_MAP below as an explicit,
-- readable list. Fuzzy matching does not happen inside this script;
-- what you see in the map is what gets assigned.
--
-- A string is in the map only if it scored >= 0.85 AND beat the
-- runner-up by >= 0.05. That margin rule matters: "Propak" ties at 0.90
-- between Propak Supply Chain Services and AK TRANSPORTATION (the
-- matcher strips "transportation" as a stop word, leaving "ak", which
-- "propak" contains). Without the margin, 26 loads would have been
-- filed under the wrong broker on iteration order alone.
--
--   auto-assigned  481 loads  $343,417  (67 broker strings)
--   left NULL      198 loads  $133,592  (22 broker strings)
--
-- What stays unassigned, and why:
--   * "10 Roads" — 145 loads, $87,700. No customer record exists. This
--     is the one worth creating by hand; it's 73% of the unassigned money.
--   * "Propak" (26) and "TCI" (3) — genuine ties, listed above.
--   * 20 one-off brokers, 24 loads, ~$33k — no customer on file.
-- All of those land under "No customer" on Receivables and can be
-- reassigned there.
--
-- Known imperfections, accepted deliberately:
--   * 2 loads have a zero/absent amount and are skipped — an invoice
--     for $0 is noise, not history.
--   * The snapshot is a reconstruction, not the document a broker
--     received. It is marked as such so nothing mistakes it for one.
--
-- REVERSAL — everything written here is tagged, so this undoes it whole.
-- Keep this to hand before running:
--
--   UPDATE loads SET customer_id = NULL WHERE id IN (
--     SELECT load_id FROM invoices
--     WHERE snapshot->>'backfill' = 'alvys'
--       AND snapshot->>'customerFromMatch' = 'true');
--   DELETE FROM invoice_payments WHERE created_by = 'system:alvys-backfill';
--   DELETE FROM invoices         WHERE snapshot->>'backfill' = 'alvys';
--
-- The inserts run inside a transaction so a mid-way failure leaves
-- nothing behind. The verification SELECT is deliberately AFTER the
-- COMMIT: the Supabase SQL editor only surfaces the final result set,
-- so a check-then-rollback inside the transaction would not actually be
-- visible in time to act on. Commit, read the numbers, and run the two
-- DELETEs above if they disagree with the expectations.

BEGIN;

-- ── Reviewed broker -> customer map ───────────────────────────────
-- Generated by running customerMatch.ts over the distinct broker
-- strings on the orphan loads. Every row met the >=0.85 score and
-- >=0.05 margin rule. Read it; anything wrong here is wrong in 2,560
-- financial records.

CREATE TEMP TABLE broker_map (broker text PRIMARY KEY, customer_id uuid) ON COMMIT DROP;

INSERT INTO broker_map (broker, customer_id) VALUES
    ('Triple T', '42f73fc4-ad32-4cb9-a50d-d9c5a5260aca')                          -- Triple T Transport (1.00, 79 loads),
    ('ITS', 'd5d5e0a8-6d28-42db-84f0-75236b2cc89b')                               -- ITS National LLC (1.00, 73 loads),
    ('Propak Supply Chain Services', '1969d99a-64c7-4fba-999e-117b962ca36a')      -- Propak Supply Chain Services (1.00, 68 loads),
    ('River City', '0d629e6d-04f5-48e7-b03c-67009f2ad813')                        -- River City Logistics Inc (1.00, 45 loads),
    ('Freight Tec', 'd072f981-a395-4506-96dc-e28c5977e394')                       -- Freight Tec (1.00, 18 loads),
    ('Forward Air', '65e0405f-93b0-428b-8b8c-22a08a20cfe3')                       -- Forward Air (1.00, 16 loads),
    ('NFI', '05959c86-3b81-4591-8be1-e14d6fbe0fdb')                               -- NFI Industries (0.90, 13 loads),
    ('NFI Industries', '05959c86-3b81-4591-8be1-e14d6fbe0fdb')                    -- NFI Industries (1.00, 11 loads),
    ('Redbone', 'dd9ccc30-2d24-4f4a-99b7-f46d8e5f2da5')                           -- Redbone Logistics LLC (1.00, 10 loads),
    ('JTS', '10a740fc-8e27-4338-8a67-3f564fd9c542')                               -- Johanson Transportation Service (1.00, 9 loads),
    ('Freeway', '6999483c-7b7f-4424-8df4-27f574a84c26')                           -- Freeway International Logistics (1.00, 8 loads),
    ('RXO', '18405af3-a799-4298-a4b9-ec83c9c15d53')                               -- RXO (1.00, 8 loads),
    ('Worldwide Express', '906a35d4-8912-4958-85e3-24ec050a6daf')                 -- Worldwide Express (1.00, 8 loads),
    ('Ryan', '03ce63d8-9d8c-4e7d-8280-31a170da3579')                              -- Ryan Transportation Service, Inc (1.00, 6 loads),
    ('Edge Logistics', 'cd0f86cf-f760-4319-a784-a001bf76a176')                    -- Edge Logistics (1.00, 5 loads),
    ('Arrive', '684c16d8-a034-466b-bd2a-fb9acf217400')                            -- Arrive (1.00, 5 loads),
    ('PRIDE TRANSPORT', 'f77c40b9-17a9-4b7a-b973-df9eb7c077ec')                   -- PRIDE TRANSPORT (1.00, 4 loads),
    ('Lighthouse', '29cf607f-07b2-443a-9f45-a991c747fdb7')                        -- Lighthouse Recycling (0.90, 4 loads),
    ('MegaCorp Logistics', '42a79945-b1b5-4f1e-9475-430c46a2ae15')                -- MegaCorp Logistics (1.00, 4 loads),
    ('INTEGRITY Express Logistics', 'f221fd11-7b2e-4831-9e8c-4b3784f25c2f')       -- INTEGRITY Express Logistics (1.00, 4 loads),
    ('Unicron', 'efb14cea-2161-490a-87d5-023b97eec56d')                           -- Unicron Logistics Solutions LLC (1.00, 4 loads),
    ('PT', '266c3ff4-d43e-4d32-9a49-aeed1ebed305')                                -- PT Brokers (1.00, 4 loads),
    ('Sage Freight', 'c365b8f6-0019-40a9-bb56-38a514253885')                      -- Sage Freight (1.00, 3 loads),
    ('TROJAN LOGISTICS', '8c63eea5-1d7d-4e6e-bb56-94afe789788c')                  -- TROJAN LOGISTICS (1.00, 3 loads),
    ('Yoke Group, LLC', 'b8b25ddc-e15a-40ba-b168-a806f06501b3')                   -- Yoke Group, LLC (1.00, 3 loads),
    ('Echo Global Logistics', '7266a092-a71e-4abc-9ef5-468eb80d709b')             -- Echo Global Logistics (1.00, 3 loads),
    ('Redwood', 'cced40ea-db07-449b-aebf-61dbc0118f06')                           -- Redwood Logistics (1.00, 3 loads),
    ('NTG', '875ede9d-4953-4a20-8b11-3275df53f2e5')                               -- Nolan Transportation Group (1.00, 3 loads),
    ('CMI', '6ad9e185-0ac9-43e9-a771-44014765cd36')                               -- CMI Insulation (1.00, 3 loads),
    ('GlobalTranz', 'e86305b5-597c-4c1f-a424-8cf7360e4e49')                       -- GlobalTranz (1.00, 2 loads),
    ('Molo', 'eaadf11c-3a14-4313-84cb-e1083a62c6ae')                              -- Molo (1.00, 2 loads),
    ('Navajo Express Inc', '3e2cfada-9218-4160-8d57-993a01097845')                -- Navajo Express Inc (1.00, 2 loads),
    ('House of Foils', '325393b3-a82a-47af-8545-d84e4e4b2ec2')                    -- House of Foils (1.00, 2 loads),
    ('Transportation1', '02639cac-9d1f-4d4c-9ccf-a18a4b78a4d1')                   -- Transportation One (1.00, 2 loads),
    ('Edge', 'cd0f86cf-f760-4319-a784-a001bf76a176')                              -- Edge Logistics (1.00, 2 loads),
    ('Echo', '7266a092-a71e-4abc-9ef5-468eb80d709b')                              -- Echo Global Logistics (1.00, 2 loads),
    ('CXS', 'b1cc5759-a269-4d09-8d91-e169210ae842')                               -- CXS Logistics (1.00, 2 loads),
    ('Bay & Bay Transportation', 'b305d9b3-6dfe-4138-bcc3-45e7caeaa94b')          -- Bay & Bay Transportation (1.00, 2 loads),
    ('Dreamliner', 'fd103d45-1066-4b7e-8a6d-3dd510e52be1')                        -- Dreamliner (1.00, 2 loads),
    ('Argo', '4daaa33b-dc18-4095-89ed-e77909cf078f')                              -- Argo Logistics Group, LLC (1.00, 2 loads),
    ('BMM LOGISTICS', 'c82b31bf-531a-40ab-a949-49d74d10ad3d')                     -- BMM LOGISTICS (1.00, 2 loads),
    ('Giltner', 'edcec35e-7a98-4400-bb90-91874bc60506')                           -- Giltner Logistics, Inc. (1.00, 2 loads),
    ('Navajo', '3e2cfada-9218-4160-8d57-993a01097845')                            -- Navajo Express Inc (1.00, 2 loads),
    ('Vess', 'ea7bb3ae-d543-4d5f-84e5-5dd425b04507')                              -- VESS Logistics LLC (1.00, 2 loads),
    ('Spot', '9a49162c-66ae-4304-8352-deba907c1626')                              -- Spot Freight (1.00, 2 loads),
    ('Soar Transportation', 'dc06d504-f400-428d-bbbd-b52176bdb04b')               -- Soar Transportation (1.00, 1 load),
    ('loop', '8bb1cd22-d3b5-4bcf-a4d7-b69ceeafc65d')                              -- TransLoop (0.90, 1 load),
    ('BBI', '2ac7daf3-011a-4014-92e8-643092bf0a6b')                               -- BBI Logistics (1.00, 1 load),
    ('England', '55b73aa9-d96e-458c-8d91-9431f357ff71')                           -- England (1.00, 1 load),
    ('Corcoran', '19a2be36-b92e-4d04-904f-85f42568bbff')                          -- Raymond Corcoran (0.90, 1 load),
    ('Freightvana', '5e6679d2-dc6e-4093-ba5f-faebca2a580b')                       -- FreightVana (1.00, 1 load),
    ('PAM Transport Inc.', '8a3d079c-dc13-4a55-80b7-25ab14947c0a')                -- PAM Transport Inc. (1.00, 1 load),
    ('Circle', 'a4f7e422-6662-4ede-a7fa-0e0f6a072633')                            -- Circle Logistics, Inc (1.00, 1 load),
    ('Pam', '8a3d079c-dc13-4a55-80b7-25ab14947c0a')                               -- PAM Transport Inc. (1.00, 1 load),
    ('Megacorp', '42a79945-b1b5-4f1e-9475-430c46a2ae15')                          -- MegaCorp Logistics (1.00, 1 load),
    ('Tin Goose', 'b2f874c2-1542-4017-b7be-848bc5bc4cc3')                         -- Tin Goose Logistics (1.00, 1 load),
    ('Blue Grace', '122662cb-0eae-426d-ad86-1ac1c7e29a6f')                        -- Capacity Express (0.90, 1 load),
    ('Bay&Bay', 'b305d9b3-6dfe-4138-bcc3-45e7caeaa94b')                           -- Bay & Bay Transportation (1.00, 1 load),
    ('Traffix', 'adaecc75-ce5f-4e90-a4a1-a7c0d5bf56c6')                           -- TRAFFIX (1.00, 1 load),
    ('Axle', '187e89a5-e1a3-4f22-9a63-76e00596fd25')                              -- Axle Logistics (1.00, 1 load),
    ('Max Trans Logistics', 'e690f0d7-e5bb-49ec-9aa8-a4f08635cdd2')               -- Max Trans Logistics (1.00, 1 load),
    ('Addison', '2516fb97-1bb2-4195-bf78-bc194a514882')                           -- Addison Transportation (1.00, 1 load),
    ('Sunteck', '97246a98-e190-4883-b7b6-2dff14d95c91')                           -- Sunteck Transport (1.00, 1 load),
    ('Big G', 'e433a4c7-f1a1-4528-88f9-42dc2868dcfd')                             -- Big G Logistics (1.00, 1 load),
    ('Circle Logistics, Inc', 'a4f7e422-6662-4ede-a7fa-0e0f6a072633')             -- Circle Logistics, Inc (1.00, 1 load),
    ('ClaireIT Carriers', 'dbb5a71b-8fc7-4813-9725-a539800dd625')                 -- ClaireIT Carriers (1.00, 1 load),
    ('TQL', '34c7d790-bcd8-4557-80c5-8a2b7cfb3bfc')                               -- Total Quality Logistics (1.00, 1 load);

-- ── Invoices ──────────────────────────────────────────────────────

INSERT INTO invoices (
  org_id, load_id, customer_id, invoice_number, status, total,
  issued_at, due_at, snapshot, sent_at, sent_method
)
SELECT
  l.org_id,
  l.id,
  -- The load's own customer wins; the map only fills a gap.
  COALESCE(l.customer_id, bm.customer_id),
  -- Same numbering rule the app uses: the load's internal id. Verified
  -- to collide with no existing invoice number and to be unique within
  -- this set, which the two unique indexes on invoices would enforce
  -- anyway.
  l.internal_load_id::text,
  CASE WHEN l.billing_status = 'paid' THEN 'paid' ELSE 'sent' END,
  COALESCE(l.total_billable, l.load_price, 0),
  pickup.issued_at,
  pickup.issued_at + interval '30 days',
  jsonb_build_object(
    'backfill',     'alvys',
    -- Tagged so the reversal can un-set exactly the customers this
    -- script assigned, and no others.
    'customerFromMatch', (l.customer_id IS NULL AND bm.customer_id IS NOT NULL),
    'backfillNote', 'Reconstructed from the load record. Invoiced in Alvys before FleetCal owned billing; this is not the document the broker received.',
    'loadNumber',   COALESCE(l.load_num, l.internal_load_id::text),
    'brokerName',   COALESCE(l.broker, ''),
    'pickupDate',   to_char(pickup.issued_at, 'YYYY-MM-DD'),
    'totalCharges', COALESCE(l.total_billable, l.load_price, 0),
    'balanceDue',   COALESCE(l.total_billable, l.load_price, 0),
    'stops',        '[]'::jsonb,
    'lineItems',    jsonb_build_array(jsonb_build_object(
                      'label',  'Linehaul',
                      'amount', COALESCE(l.total_billable, l.load_price, 0)
                    ))
  ),
  -- "Assume the invoice was sent on the load date."
  pickup.issued_at,
  'manual'
FROM loads l
CROSS JOIN LATERAL (
  -- Pickup leg = lowest leg_index. events.start is naive Mountain wall
  -- time (see schema.sql), so it needs the zone applied rather than
  -- being read as UTC — otherwise every date shifts by 6-7 hours and
  -- some land on the previous day.
  SELECT (e.start::timestamp AT TIME ZONE 'America/Denver') AS issued_at
  FROM events e
  WHERE e.load_id = l.id
  ORDER BY e.leg_index NULLS LAST, e.start
  LIMIT 1
) AS pickup
LEFT JOIN broker_map bm ON bm.broker = btrim(l.broker)
WHERE l.org_id = 'org_3Ck09w6LuEjiX4WgxJEPyiyjuXN'
  AND l.deleted_at IS NULL
  AND l.billing_status IN ('invoiced', 'paid')
  AND COALESCE(l.total_billable, l.load_price, 0) > 0
  -- Idempotent: re-running inserts nothing, and it never competes with
  -- an invoice the app generated.
  AND NOT EXISTS (SELECT 1 FROM invoices i WHERE i.load_id = l.id);

-- ── Allocations for the already-paid ones ─────────────────────────

INSERT INTO invoice_payments (
  org_id, invoice_id, proof_id, amount, paid_on, method, note, created_by
)
SELECT
  i.org_id,
  i.id,
  NULL,                       -- no evidence exists for these; that's honest
  i.total,
  (i.issued_at AT TIME ZONE 'UTC')::date,
  NULL,
  'Alvys-era payment, backfilled from the load record',
  'system:alvys-backfill'
FROM invoices i
WHERE i.snapshot->>'backfill' = 'alvys'
  AND i.status = 'paid'
  AND NOT EXISTS (
    SELECT 1 FROM invoice_payments p WHERE p.invoice_id = i.id
  );

-- Mirror the ledger onto the invoice summary columns, matching
-- recomputeInvoicePaid() exactly (paid_at = paid_on at 12:00Z, method
-- NULL) so the first later recompute is a no-op rather than a change.
UPDATE invoices i
SET paid_amount = p.amount,
    paid_at     = ((p.paid_on::text || 'T12:00:00Z')::timestamptz),
    paid_method = NULL
FROM invoice_payments p
WHERE p.invoice_id = i.id
  AND p.created_by = 'system:alvys-backfill'
  AND i.snapshot->>'backfill' = 'alvys';

-- ── Point the loads at the same customers ─────────────────────────
-- Without this the invoice knows its broker but the load still reads
-- "no customer" everywhere else in the app — Billing, the calendar, the
-- load modal. Same map, same rows, only ever filling a NULL.

UPDATE loads l
SET customer_id = bm.customer_id
FROM broker_map bm
WHERE l.org_id = 'org_3Ck09w6LuEjiX4WgxJEPyiyjuXN'
  AND l.customer_id IS NULL
  AND btrim(l.broker) = bm.broker
  AND EXISTS (
    SELECT 1 FROM invoices i
    WHERE i.load_id = l.id AND i.snapshot->>'backfill' = 'alvys'
  );

-- ── Verify AFTER committing ───────────────────────────────────────
-- One result set, because the editor shows only the last one. Read it
-- against the expectations at the top of this file; if it disagrees,
-- run the two DELETEs from the REVERSAL block.

COMMIT;

SELECT
  (SELECT count(*)                                    FROM invoices WHERE snapshot->>'backfill' = 'alvys')                        AS invoices_inserted,
  (SELECT count(*)                                    FROM invoices WHERE snapshot->>'backfill' = 'alvys' AND status = 'sent')    AS status_sent,
  (SELECT count(*)                                    FROM invoices WHERE snapshot->>'backfill' = 'alvys' AND status = 'paid')    AS status_paid,
  (SELECT round(sum(total)::numeric, 2)               FROM invoices WHERE snapshot->>'backfill' = 'alvys')                        AS total_backfilled,
  (SELECT round(sum(total)::numeric, 2)               FROM invoices WHERE snapshot->>'backfill' = 'alvys' AND status = 'sent')    AS open_added,
  (SELECT count(*)                                    FROM invoices WHERE snapshot->>'backfill' = 'alvys' AND customer_id IS NULL) AS no_customer,
  (SELECT count(*)                                    FROM invoices WHERE snapshot->>'customerFromMatch' = 'true')                 AS customer_from_map,
  (SELECT min(issued_at)::date                        FROM invoices WHERE snapshot->>'backfill' = 'alvys')                        AS earliest,
  (SELECT max(issued_at)::date                        FROM invoices WHERE snapshot->>'backfill' = 'alvys')                        AS latest,
  (SELECT count(*)                                    FROM invoice_payments WHERE created_by = 'system:alvys-backfill')           AS allocations_inserted,
  (SELECT round(sum(amount)::numeric, 2)              FROM invoice_payments WHERE created_by = 'system:alvys-backfill')           AS allocated;
