-- 20260607_trailers_category_freeform.sql
--
-- Drop the CHECK constraint on trailers.category so dispatchers can
-- define their own categories ("Container", "Tanker", "Dump", etc.)
-- from the Trailer Directory's Categories dialog. The seed list
-- (TRAILER_CATEGORIES in @fleetcal/types) remains the default for new
-- orgs; per-org category lists are stored client-side in localStorage
-- alongside assetCategories.
--
-- Idempotent: tries both known constraint names. If the live DB has a
-- Postgres-autogenerated name, surface it with the query embedded in
-- 20260524_trailer_category_reefer.sql and add it to the DROP list.

ALTER TABLE trailers DROP CONSTRAINT IF EXISTS trailers_category_check;
ALTER TABLE trailers DROP CONSTRAINT IF EXISTS trailers_category_chk;
